### ISSUE TITLE
Add tree bark output to IE Sawmill

### ISSUE THREAD

**Issue by dragonshardz** [dragonshardz/dpt7#16]

**Comment by neogeo0823** [comment]
I'm unsure if this is doable. Wiki shows the recipe format for cutting as: 
`<recipetype:create:cutting>.addRecipe(String name, IItemStack output, IIngredient input, @Optional(100) int duration)`
where item output doesn't seem to support multiple outputs. 

Conversely, as an example, the milling recipe type is listed as:
`<recipetype:create:milling>.addRecipe(String name, MCWeightedItemStack[] output, IIngredient input, @Optional(100) int duration)`
Which *does* support multiple outputs, as shown in the given example:
`<recipetype:create:milling>.addRecipe("milling_test", [<item:minecraft:diamond>, <item:minecraft:apple> % 45], <item:minecraft:dirt>)`

Attempting the multiple outputs anyway with test recipe:
`<recipetype:create:cutting>.addRecipe("cutting_test", [<item:minecraft:diamond>, <item:minecraft:oak_log> % 50], <item:minecraft:diamond>)`
outputs an error on reload of: 
"No matching method found for addRecipe: Parameter 2: Cannot cast MCWeightedItemStack to IIngredient"

Unsure if there's a way to force output to be MCWeightedItemStack[] output instead of IItemStack output.

**Comment by dragonshardz** [comment]
There's not a way to force different output types. It should be possible to do an arrayed output, EG: `<recipetype:create:cutting>.addRecipe("oakbark", [<item:minecraft:stripped_oak_log>,<item:farmersdelight:tree_bark>], <item:minecraft:oak_log>);`

**Comment by dragonshardz** [comment]
And that doesn't work, because fuck everything, one input, one output.

**Comment by dragonshardz** [comment]
Actually, this should be possible with IE's Sawmill, I guess.
